In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
type(a)

numpy.ndarray

In [5]:
a = np.array([1,2,3], dtype = float)
print(a)

[1. 2. 3.]


In [6]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
type(b)

numpy.ndarray

In [8]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [11]:
c.ndim

2

In [12]:
d = np.array([[[[1,2,3], [4,5,6], [7,8,9]]]])
print(d)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [13]:
d.ndim

4

In [14]:
a

array([1., 2., 3.])

In [15]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
c.shape

(3, 3)

In [18]:
a

array([1., 2., 3.])

In [19]:
a.dtype

dtype('float64')

In [20]:
a_int = np.array([1.1,2.1,3.4])
print(a_int)

[1.1 2.1 3.4]


In [21]:
a_int.dtype

dtype('float64')

In [22]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
a.ndim

2

In [24]:
a[0,3]

4

In [25]:
a[1,0]

8

In [26]:
a[1,5]

13

In [27]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
a[:,0]

array([1, 8])

In [29]:
a[:,0]

array([1, 8])

In [30]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [31]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
np.full((3,3), 50, dtype='float64')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [35]:
np.full((3,3), 50, dtype='int32')

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [36]:
np.random.rand(4,4)

array([[0.97688475, 0.11213598, 0.52982373, 0.67015415],
       [0.97609957, 0.2200847 , 0.69932716, 0.34036355],
       [0.95262839, 0.93568708, 0.15761424, 0.48096673],
       [0.32170498, 0.56241197, 0.76281619, 0.55750814]])

In [37]:
np.random.randint(-4,1, size=(3,3))

array([[-1, -3, -1],
       [-2, -1, -1],
       [-2,  0, -2]])

In [38]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [40]:
a+2

array([3, 4, 5, 6])

In [41]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [42]:
a

array([1, 2, 3, 4])

In [43]:
a.min()

1

In [44]:
np.min(a)

1

In [45]:
a.max()

4

In [46]:
np.max(a)

4

In [47]:
a.mean()

2.5

In [48]:
np.mean(a)

2.5

In [49]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
np.max(a)

8

In [51]:
a.max()

8

In [52]:
np.min(a)

1

In [53]:
np.mean(a)

4.5

In [54]:
np.sum(a)

36

In [55]:
np.max(a, axis=1)

array([4, 8])

In [56]:
np.max(a, axis=0)

array([5, 6, 7, 8])

In [57]:
np.min(a, axis=0)

array([1, 2, 3, 4])

In [58]:
np.min(a, axis=1)

array([1, 5])

In [59]:
np.sum(a, axis=1)

array([10, 26])

In [60]:
np.sum(a, axis=0)

array([ 6,  8, 10, 12])